[package]
name = "loopover"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
crossterm = "0.28.1"
dirs = "5.0.1"
rand = "0.8.5"
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.125"
termint = "0.5.0"
